apiVersion: apps/v1
kind: Deployment
metadata:
  name: gender-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gender
  template:
    metadata:
      labels:
        app: gender
    spec:
      containers:
        - name: car-emission
          image: sathwik10/gender2
          ports:
            - containerPort: 5000
